# Generated by Django 4.0.4 on 2022-05-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museventApplication', '0002_alter_visitor_options_alter_visitor_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='birthdate',
        ),
    ]
