# Generated by Django 4.0.4 on 2022-06-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museventApplication', '0003_remove_visitor_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='museventApplication.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
